#!/usr/bin/env python3


include: "rules/pull_busco_mapping.smk"
include: "rules/pull_ncbi_taxonomy.smk"
include: "rules/get_oatk_hmm_map.smk"


rule target:
    default_target: True
    input:
        rules.download_busco_placement_file.output,
        rules.expand_taxdump.output,
        rules.get_oatk_hmm_map.output,
