get_remote_files:
	get-remote-files --help

test:
	atol-reference-data-lookups \
		--nodes resources/new_taxdump/nodes.dmp \
		--names resources/new_taxdump/names.dmp \
		--taxids_to_busco_dataset_mapping resources/mapping_taxids-busco_dataset_name.eukaryota_odb10.2019-12-16.txt.tar.gz